export interface UserData {
  id: string;
  nombre: string;
  apellido: string;
  email: string;
  perfiles: string[];
  estado: 'Activo' | 'Inactivo';
}

// Profile options
export const profileOptions = [
  'Admin',
  'User',
  'Operator',
  'Manager',
  'Technician',
  'Support',
  'Developer',
  'Tester',
  'Guest',
];

// Status options
export const statusOptions = ['Activo', 'Inactivo'];

// Generate dummy user data
export const dummyUserData: UserData[] = [
  {
    id: '1',
    nombre: 'Juan',
    apellido: 'Pérez',
    email: 'juan.perez@example.com',
    perfiles: ['Admin', 'Developer'],
    estado: 'Activo',
  },
  {
    id: '2',
    nombre: 'María',
    apellido: 'González',
    email: 'maria.gonzalez@example.com',
    perfiles: ['User', 'Tester'],
    estado: 'Activo',
  },
  {
    id: '3',
    nombre: 'Carlos',
    apellido: 'Rodríguez',
    email: 'carlos.rodriguez@example.com',
    perfiles: ['Manager', 'Operator'],
    estado: 'Inactivo',
  },
  {
    id: '4',
    nombre: 'Ana',
    apellido: 'Martínez',
    email: 'ana.martinez@example.com',
    perfiles: ['Support'],
    estado: 'Activo',
  },
  {
    id: '5',
    nombre: 'Luis',
    apellido: 'Hernández',
    email: 'luis.hernandez@example.com',
    perfiles: ['Technician'],
    estado: 'Inactivo',
  },
  {
    id: '6',
    nombre: 'Laura',
    apellido: 'López',
    email: 'laura.lopez@example.com',
    perfiles: ['Developer', 'Tester'],
    estado: 'Activo',
  },
  {
    id: '7',
    nombre: 'Pedro',
    apellido: 'Sánchez',
    email: 'pedro.sanchez@example.com',
    perfiles: ['User'],
    estado: 'Activo',
  },
  {
    id: '8',
    nombre: 'Sofía',
    apellido: 'Ramírez',
    email: 'sofia.ramirez@example.com',
    perfiles: ['Admin', 'Manager'],
    estado: 'Activo',
  },
  {
    id: '9',
    nombre: 'Miguel',
    apellido: 'Torres',
    email: 'miguel.torres@example.com',
    perfiles: ['Operator'],
    estado: 'Inactivo',
  },
  {
    id: '10',
    nombre: 'Elena',
    apellido: 'Flores',
    email: 'elena.flores@example.com',
    perfiles: ['Support', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '11',
    nombre: 'Javier',
    apellido: 'Díaz',
    email: 'javier.diaz@example.com',
    perfiles: ['Developer'],
    estado: 'Activo',
  },
  {
    id: '12',
    nombre: 'Carmen',
    apellido: 'Morales',
    email: 'carmen.morales@example.com',
    perfiles: ['Tester', 'Support'],
    estado: 'Inactivo',
  },
  {
    id: '13',
    nombre: 'Alberto',
    apellido: 'Gutiérrez',
    email: 'alberto.gutierrez@example.com',
    perfiles: ['Manager', 'Admin'],
    estado: 'Activo',
  },
  {
    id: '14',
    nombre: 'Isabel',
    apellido: 'Vázquez',
    email: 'isabel.vazquez@example.com',
    perfiles: ['User', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '15',
    nombre: 'Fernando',
    apellido: 'Reyes',
    email: 'fernando.reyes@example.com',
    perfiles: ['Technician'],
    estado: 'Inactivo',
  },
  {
    id: '16',
    nombre: 'Raquel',
    apellido: 'Castro',
    email: 'raquel.castro@example.com',
    perfiles: ['Developer', 'Admin'],
    estado: 'Activo',
  },
  {
    id: '17',
    nombre: 'Francisco',
    apellido: 'Ortiz',
    email: 'francisco.ortiz@example.com',
    perfiles: ['Tester'],
    estado: 'Activo',
  },
  {
    id: '18',
    nombre: 'Lucía',
    apellido: 'Ramos',
    email: 'lucia.ramos@example.com',
    perfiles: ['Support', 'Manager'],
    estado: 'Inactivo',
  },
  {
    id: '19',
    nombre: 'Antonio',
    apellido: 'Jiménez',
    email: 'antonio.jimenez@example.com',
    perfiles: ['Operator', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '20',
    nombre: 'Silvia',
    apellido: 'Ruiz',
    email: 'silvia.ruiz@example.com',
    perfiles: ['User', 'Support'],
    estado: 'Activo',
  },
  {
    id: '21',
    nombre: 'Pablo',
    apellido: 'Navarro',
    email: 'pablo.navarro@example.com',
    perfiles: ['Developer'],
    estado: 'Inactivo',
  },
  {
    id: '22',
    nombre: 'Cristina',
    apellido: 'Molina',
    email: 'cristina.molina@example.com',
    perfiles: ['Manager'],
    estado: 'Activo',
  },
  {
    id: '23',
    nombre: 'Alejandro',
    apellido: 'Serrano',
    email: 'alejandro.serrano@example.com',
    perfiles: ['Admin', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '24',
    nombre: 'Natalia',
    apellido: 'Romero',
    email: 'natalia.romero@example.com',
    perfiles: ['Tester', 'Developer'],
    estado: 'Activo',
  },
  {
    id: '25',
    nombre: 'Mario',
    apellido: 'Sanz',
    email: 'mario.sanz@example.com',
    perfiles: ['User'],
    estado: 'Inactivo',
  },
  {
    id: '26',
    nombre: 'Diana',
    apellido: 'Rubio',
    email: 'diana.rubio@example.com',
    perfiles: ['Support', 'Admin'],
    estado: 'Activo',
  },
  {
    id: '27',
    nombre: 'Roberto',
    apellido: 'Méndez',
    email: 'roberto.mendez@example.com',
    perfiles: ['Manager', 'Operator'],
    estado: 'Activo',
  },
  {
    id: '28',
    nombre: 'Patricia',
    apellido: 'Ortega',
    email: 'patricia.ortega@example.com',
    perfiles: ['Tester'],
    estado: 'Inactivo',
  },
  {
    id: '29',
    nombre: 'Daniel',
    apellido: 'Iglesias',
    email: 'daniel.iglesias@example.com',
    perfiles: ['Developer', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '30',
    nombre: 'Sara',
    apellido: 'Marín',
    email: 'sara.marin@example.com',
    perfiles: ['User', 'Tester'],
    estado: 'Activo',
  },
  {
    id: '31',
    nombre: 'José',
    apellido: 'Gómez',
    email: 'jose.gomez@example.com',
    perfiles: ['Technician', 'Support'],
    estado: 'Inactivo',
  },
  {
    id: '32',
    nombre: 'Alicia',
    apellido: 'Soto',
    email: 'alicia.soto@example.com',
    perfiles: ['Admin'],
    estado: 'Activo',
  },
  {
    id: '33',
    nombre: 'Víctor',
    apellido: 'Gil',
    email: 'victor.gil@example.com',
    perfiles: ['Operator'],
    estado: 'Activo',
  },
  {
    id: '34',
    nombre: 'Eva',
    apellido: 'Muñoz',
    email: 'eva.munoz@example.com',
    perfiles: ['Developer', 'Manager'],
    estado: 'Activo',
  },
  {
    id: '35',
    nombre: 'Santiago',
    apellido: 'Vargas',
    email: 'santiago.vargas@example.com',
    perfiles: ['Support'],
    estado: 'Inactivo',
  },
  {
    id: '36',
    nombre: 'Marta',
    apellido: 'Delgado',
    email: 'marta.delgado@example.com',
    perfiles: ['Tester', 'User'],
    estado: 'Activo',
  },
  {
    id: '37',
    nombre: 'Óscar',
    apellido: 'Cruz',
    email: 'oscar.cruz@example.com',
    perfiles: ['Admin', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '38',
    nombre: 'Beatriz',
    apellido: 'León',
    email: 'beatriz.leon@example.com',
    perfiles: ['Developer'],
    estado: 'Inactivo',
  },
  {
    id: '39',
    nombre: 'Adrián',
    apellido: 'Pardo',
    email: 'adrian.pardo@example.com',
    perfiles: ['Manager'],
    estado: 'Activo',
  },
  {
    id: '40',
    nombre: 'Nuria',
    apellido: 'Campos',
    email: 'nuria.campos@example.com',
    perfiles: ['User', 'Operator'],
    estado: 'Activo',
  },
  {
    id: '41',
    nombre: 'Jorge',
    apellido: 'Blanco',
    email: 'jorge.blanco@example.com',
    perfiles: ['Support', 'Tester'],
    estado: 'Inactivo',
  },
  {
    id: '42',
    nombre: 'Andrea',
    apellido: 'Vidal',
    email: 'andrea.vidal@example.com',
    perfiles: ['Developer', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '43',
    nombre: 'Sergio',
    apellido: 'Santos',
    email: 'sergio.santos@example.com',
    perfiles: ['Admin'],
    estado: 'Activo',
  },
  {
    id: '44',
    nombre: 'Claudia',
    apellido: 'Herrero',
    email: 'claudia.herrero@example.com',
    perfiles: ['Manager', 'Technician'],
    estado: 'Inactivo',
  },
  {
    id: '45',
    nombre: 'David',
    apellido: 'Núñez',
    email: 'david.nunez@example.com',
    perfiles: ['User'],
    estado: 'Activo',
  },
  {
    id: '46',
    nombre: 'Mónica',
    apellido: 'Medina',
    email: 'monica.medina@example.com',
    perfiles: ['Tester', 'Support'],
    estado: 'Activo',
  },
  {
    id: '47',
    nombre: 'Iván',
    apellido: 'Garrido',
    email: 'ivan.garrido@example.com',
    perfiles: ['Developer', 'Admin'],
    estado: 'Inactivo',
  },
  {
    id: '48',
    nombre: 'Lorena',
    apellido: 'Martos',
    email: 'lorena.martos@example.com',
    perfiles: ['Operator'],
    estado: 'Activo',
  },
  {
    id: '49',
    nombre: 'Rafael',
    apellido: 'Cano',
    email: 'rafael.cano@example.com',
    perfiles: ['Technician', 'Manager'],
    estado: 'Activo',
  },
  {
    id: '50',
    nombre: 'Marina',
    apellido: 'Alonso',
    email: 'marina.alonso@example.com',
    perfiles: ['Support', 'User'],
    estado: 'Inactivo',
  },
  {
    id: '51',
    nombre: 'Álvaro',
    apellido: 'Benítez',
    email: 'alvaro.benitez@example.com',
    perfiles: ['Admin'],
    estado: 'Activo',
  },
  {
    id: '52',
    nombre: 'Raúl',
    apellido: 'Aguilar',
    email: 'raul.aguilar@example.com',
    perfiles: ['Developer', 'Tester'],
    estado: 'Activo',
  },
  {
    id: '53',
    nombre: 'Susana',
    apellido: 'Soler',
    email: 'susana.soler@example.com',
    perfiles: ['Manager'],
    estado: 'Inactivo',
  },
  {
    id: '54',
    nombre: 'Gabriel',
    apellido: 'Moya',
    email: 'gabriel.moya@example.com',
    perfiles: ['User', 'Support'],
    estado: 'Activo',
  },
  {
    id: '55',
    nombre: 'Esther',
    apellido: 'Esteban',
    email: 'esther.esteban@example.com',
    perfiles: ['Technician'],
    estado: 'Activo',
  },
  {
    id: '56',
    nombre: 'Hugo',
    apellido: 'Vega',
    email: 'hugo.vega@example.com',
    perfiles: ['Operator', 'Admin'],
    estado: 'Inactivo',
  },
  {
    id: '57',
    nombre: 'Miriam',
    apellido: 'Rico',
    email: 'miriam.rico@example.com',
    perfiles: ['Developer'],
    estado: 'Activo',
  },
  {
    id: '58',
    nombre: 'Guillermo',
    apellido: 'Lara',
    email: 'guillermo.lara@example.com',
    perfiles: ['Tester', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '59',
    nombre: 'Olga',
    apellido: 'Pascual',
    email: 'olga.pascual@example.com',
    perfiles: ['Support', 'Manager'],
    estado: 'Inactivo',
  },
  {
    id: '60',
    nombre: 'Ignacio',
    apellido: 'Sierra',
    email: 'ignacio.sierra@example.com',
    perfiles: ['User'],
    estado: 'Activo',
  },
  {
    id: '61',
    nombre: 'Verónica',
    apellido: 'Robles',
    email: 'veronica.robles@example.com',
    perfiles: ['Admin', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '62',
    nombre: 'Eduardo',
    apellido: 'Mora',
    email: 'eduardo.mora@example.com',
    perfiles: ['Developer', 'Operator'],
    estado: 'Inactivo',
  },
  {
    id: '63',
    nombre: 'Paula',
    apellido: 'Bravo',
    email: 'paula.bravo@example.com',
    perfiles: ['Manager'],
    estado: 'Activo',
  },
  {
    id: '64',
    nombre: 'Felipe',
    apellido: 'Arias',
    email: 'felipe.arias@example.com',
    perfiles: ['Tester', 'Support'],
    estado: 'Activo',
  },
  {
    id: '65',
    nombre: 'Irene',
    apellido: 'Gallego',
    email: 'irene.gallego@example.com',
    perfiles: ['User', 'Guest'],
    estado: 'Inactivo',
  },
  {
    id: '66',
    nombre: 'Samuel',
    apellido: 'Durán',
    email: 'samuel.duran@example.com',
    perfiles: ['Admin'],
    estado: 'Activo',
  },
  {
    id: '67',
    nombre: 'Noelia',
    apellido: 'Cabrera',
    email: 'noelia.cabrera@example.com',
    perfiles: ['Developer', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '68',
    nombre: 'Héctor',
    apellido: 'Carrasco',
    email: 'hector.carrasco@example.com',
    perfiles: ['Support'],
    estado: 'Inactivo',
  },
  {
    id: '69',
    nombre: 'Julia',
    apellido: 'Calvo',
    email: 'julia.calvo@example.com',
    perfiles: ['Manager', 'User'],
    estado: 'Activo',
  },
  {
    id: '70',
    nombre: 'Joel',
    apellido: 'Guerrero',
    email: 'joel.guerrero@example.com',
    perfiles: ['Operator'],
    estado: 'Activo',
  },
  {
    id: '71',
    nombre: 'Aurora',
    apellido: 'Crespo',
    email: 'aurora.crespo@example.com',
    perfiles: ['Tester', 'Admin'],
    estado: 'Inactivo',
  },
  {
    id: '72',
    nombre: 'Marc',
    apellido: 'Nieto',
    email: 'marc.nieto@example.com',
    perfiles: ['Developer'],
    estado: 'Activo',
  },
  {
    id: '73',
    nombre: 'Nerea',
    apellido: 'Prieto',
    email: 'nerea.prieto@example.com',
    perfiles: ['Support', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '74',
    nombre: 'Martín',
    apellido: 'Sáez',
    email: 'martin.saez@example.com',
    perfiles: ['User'],
    estado: 'Inactivo',
  },
  {
    id: '75',
    nombre: 'Lidia',
    apellido: 'Vicente',
    email: 'lidia.vicente@example.com',
    perfiles: ['Manager', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '76',
    nombre: 'Gonzalo',
    apellido: 'Velasco',
    email: 'gonzalo.velasco@example.com',
    perfiles: ['Admin', 'Operator'],
    estado: 'Activo',
  },
  {
    id: '77',
    nombre: 'Elisa',
    apellido: 'Román',
    email: 'elisa.roman@example.com',
    perfiles: ['Developer', 'Tester'],
    estado: 'Inactivo',
  },
  {
    id: '78',
    nombre: 'Rubén',
    apellido: 'Pastor',
    email: 'ruben.pastor@example.com',
    perfiles: ['Support'],
    estado: 'Activo',
  },
  {
    id: '79',
    nombre: 'Celia',
    apellido: 'Hidalgo',
    email: 'celia.hidalgo@example.com',
    perfiles: ['Technician', 'User'],
    estado: 'Activo',
  },
  {
    id: '80',
    nombre: 'Nicolás',
    apellido: 'Sáez',
    email: 'nicolas.saez@example.com',
    perfiles: ['Manager'],
    estado: 'Inactivo',
  },
  {
    id: '81',
    nombre: 'Rocío',
    apellido: 'Luque',
    email: 'rocio.luque@example.com',
    perfiles: ['Admin', 'Support'],
    estado: 'Activo',
  },
  {
    id: '82',
    nombre: 'Leonardo',
    apellido: 'Rivero',
    email: 'leonardo.rivero@example.com',
    perfiles: ['Operator'],
    estado: 'Activo',
  },
  {
    id: '83',
    nombre: 'Ángela',
    apellido: 'Santana',
    email: 'angela.santana@example.com',
    perfiles: ['Developer', 'Tester'],
    estado: 'Inactivo',
  },
  {
    id: '84',
    nombre: 'Marco',
    apellido: 'Parra',
    email: 'marco.parra@example.com',
    perfiles: ['User'],
    estado: 'Activo',
  },
  {
    id: '85',
    nombre: 'Inés',
    apellido: 'Requena',
    email: 'ines.requena@example.com',
    perfiles: ['Support', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '86',
    nombre: 'César',
    apellido: 'Duque',
    email: 'cesar.duque@example.com',
    perfiles: ['Manager', 'Admin'],
    estado: 'Inactivo',
  },
  {
    id: '87',
    nombre: 'Lola',
    apellido: 'Caballero',
    email: 'lola.caballero@example.com',
    perfiles: ['Guest'],
    estado: 'Activo',
  },
  {
    id: '88',
    nombre: 'Arnau',
    apellido: 'Merino',
    email: 'arnau.merino@example.com',
    perfiles: ['Developer', 'Operator'],
    estado: 'Activo',
  },
  {
    id: '89',
    nombre: 'Helena',
    apellido: 'Zamora',
    email: 'helena.zamora@example.com',
    perfiles: ['Tester'],
    estado: 'Inactivo',
  },
  {
    id: '90',
    nombre: 'Tomás',
    apellido: 'Valencia',
    email: 'tomas.valencia@example.com',
    perfiles: ['User', 'Support'],
    estado: 'Activo',
  },
  {
    id: '91',
    nombre: 'Carolina',
    apellido: 'Miranda',
    email: 'carolina.miranda@example.com',
    perfiles: ['Admin', 'Technician'],
    estado: 'Activo',
  },
  {
    id: '92',
    nombre: 'Íñigo',
    apellido: 'Bernal',
    email: 'inigo.bernal@example.com',
    perfiles: ['Manager'],
    estado: 'Inactivo',
  },
  {
    id: '93',
    nombre: 'Valeria',
    apellido: 'Peña',
    email: 'valeria.pena@example.com',
    perfiles: ['Developer', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '94',
    nombre: 'Mateo',
    apellido: 'Pons',
    email: 'mateo.pons@example.com',
    perfiles: ['Operator', 'Tester'],
    estado: 'Activo',
  },
  {
    id: '95',
    nombre: 'Sandra',
    apellido: 'Estévez',
    email: 'sandra.estevez@example.com',
    perfiles: ['Support'],
    estado: 'Inactivo',
  },
  {
    id: '96',
    nombre: 'Bruno',
    apellido: 'Lozano',
    email: 'bruno.lozano@example.com',
    perfiles: ['User', 'Admin'],
    estado: 'Activo',
  },
  {
    id: '97',
    nombre: 'Carla',
    apellido: 'Luna',
    email: 'carla.luna@example.com',
    perfiles: ['Technician'],
    estado: 'Activo',
  },
  {
    id: '98',
    nombre: 'Aitor',
    apellido: 'Bermúdez',
    email: 'aitor.bermudez@example.com',
    perfiles: ['Manager', 'Developer'],
    estado: 'Inactivo',
  },
  {
    id: '99',
    nombre: 'Míriam',
    apellido: 'Téllez',
    email: 'miriam.tellez@example.com',
    perfiles: ['Tester', 'Support'],
    estado: 'Activo',
  },
  {
    id: '100',
    nombre: 'Oliver',
    apellido: 'Arroyo',
    email: 'oliver.arroyo@example.com',
    perfiles: ['User'],
    estado: 'Activo',
  },
  {
    id: '101',
    nombre: 'Daniela',
    apellido: 'Carmona',
    email: 'daniela.carmona@example.com',
    perfiles: ['Admin', 'Operator'],
    estado: 'Inactivo',
  },
  {
    id: '102',
    nombre: 'Adriana',
    apellido: 'Toledo',
    email: 'adriana.toledo@example.com',
    perfiles: ['Developer'],
    estado: 'Activo',
  },
  {
    id: '103',
    nombre: 'Enrique',
    apellido: 'Cordero',
    email: 'enrique.cordero@example.com',
    perfiles: ['Support', 'Guest'],
    estado: 'Activo',
  },
  {
    id: '104',
    nombre: 'Luciana',
    apellido: 'Ferrer',
    email: 'luciana.ferrer@example.com',
    perfiles: ['Manager', 'Technician'],
    estado: 'Inactivo',
  },
  {
    id: '105',
    nombre: 'Ricardo',
    apellido: 'Paredes',
    email: 'ricardo.paredes@example.com',
    perfiles: ['Tester', 'User'],
    estado: 'Activo',
  },
];
